In [76]:
!pwd
import warnings
warnings.filterwarnings('ignore')
%load_ext autoreload
%autoreload 2

/home/tomi/code/Harlequinht
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [82]:
!ls

 2_cleaning.csv
 2_cleaning.csv:Zone.Identifier
 combined_data
'Concat Data.ipynb'
'Deep Learning model.ipynb'
 Feature_Engineering_Clean-Copy1.ipynb
 Feature_Engineering_Clean.ipynb
'flat_without_missint_test1 (1).csv'
'flat_without_missint_test1 (1).csv:Zone.Identifier'
'Horse Model Data - raw_data.csv'
'Horse Model Data - raw_data.csv:Zone.Identifier'
 modelling.csv
'Modelling_testing Dirty.ipynb'
 Untitled.ipynb
 which_horse
'which_horse_flat -tomi0703.ipynb'
'Whose_Horse . csv'
'Whose Horse . csv.zip'

In [77]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# import numpy as np
# from sklearn.model_selection import train_test_split

In [149]:
import pandas as pd
import numpy as np
import sklearn.model_selection as model_selection
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.optimizers import Adam

In [187]:
from tensorflow.keras import Sequential, layers
from tensorflow.keras import metrics
from tensorflow.keras.layers import Normalization 
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
import datetime as dt
from tensorflow.keras import models

In [151]:
from tensorflow.keras.callbacks import EarlyStopping

In [204]:
df = pd.read_csv('2_cleaning.csv')

In [205]:
df.columns

Index(['meeting_id', 'date', 'event_number', 'distance',
       'distance_raw_furlongs', 'total_prize_money', 'track_type', 'barrier',
       'number', 'finish_position', 'win_or_lose', 'failed_to_finish_reason',
       'margin', 'gear', 'jockey_allowance', 'handicap_weight', 'jockey_id',
       'tainer_id', 'dslr', 'horse_id', 'age', 'birth_date', 'official rating',
       'wfa', 'weight_adjustment', 'betfair_starting_price',
       'pre_race_master_rating_int', 'starting_price', 'track_condition_FAST',
       'track_condition_FIRM', 'track_condition_GOOD',
       'track_condition_GOOD TO FIRM', 'track_condition_GOOD TO SOFT',
       'track_condition_GOOD TO YIELDING', 'track_condition_HEAVY',
       'track_condition_SLOW', 'track_condition_SOFT',
       'track_condition_STANDARD', 'track_condition_STANDARD TO FAST',
       'track_condition_STANDARD TO SLOW', 'race_type_FLAT',
       'race_type_NATIONAL_HUNT_FLAT', 'race_class_1', 'race_class_2',
       'race_class_3', 'race_class_4', 'race_class_5', 'race_class_6',
       'race_class_7', 'race_class_normalised_Claiming',
       'race_class_normalised_Conditions', 'race_class_normalised_Grade 1',
       'race_class_normalised_Grade 2', 'race_class_normalised_Group 1',
       'race_class_normalised_Group 2', 'race_class_normalised_Group 3',
       'race_class_normalised_Handicap', 'race_class_normalised_Listed',
       'race_class_normalised_Maiden', 'race_class_normalised_NHF',
       'race_class_normalised_Novice', 'race_class_normalised_Selling',
       'race_class_normalised_nan', 'life_days', 'current_age'],
      dtype='object')

# training data

In [210]:
X_train = df.loc[(df['date'] < '2023-01-01')]

In [218]:
y_train_tmp = df.loc[(df['date'] < '2023-01-01')]

In [219]:
y_train = y_train_tmp['win_or_lose']

In [221]:
X_train = X_train.drop(['win_or_lose', 'date', 'birth_date'], axis = 1)

KeyError: "['win_or_lose', 'date', 'birth_date'] not found in axis"

In [223]:
X_train.columns

Index(['meeting_id', 'event_number', 'distance', 'distance_raw_furlongs',
       'total_prize_money', 'track_type', 'barrier', 'number',
       'finish_position', 'failed_to_finish_reason', 'margin', 'gear',
       'jockey_allowance', 'handicap_weight', 'jockey_id', 'tainer_id', 'dslr',
       'horse_id', 'age', 'official rating', 'wfa', 'weight_adjustment',
       'betfair_starting_price', 'pre_race_master_rating_int',
       'starting_price', 'track_condition_FAST', 'track_condition_FIRM',
       'track_condition_GOOD', 'track_condition_GOOD TO FIRM',
       'track_condition_GOOD TO SOFT', 'track_condition_GOOD TO YIELDING',
       'track_condition_HEAVY', 'track_condition_SLOW', 'track_condition_SOFT',
       'track_condition_STANDARD', 'track_condition_STANDARD TO FAST',
       'track_condition_STANDARD TO SLOW', 'race_type_FLAT',
       'race_type_NATIONAL_HUNT_FLAT', 'race_class_1', 'race_class_2',
       'race_class_3', 'race_class_4', 'race_class_5', 'race_class_6',
       'race_class_7', 'race_class_normalised_Claiming',
       'race_class_normalised_Conditions', 'race_class_normalised_Grade 1',
       'race_class_normalised_Grade 2', 'race_class_normalised_Group 1',
       'race_class_normalised_Group 2', 'race_class_normalised_Group 3',
       'race_class_normalised_Handicap', 'race_class_normalised_Listed',
       'race_class_normalised_Maiden', 'race_class_normalised_NHF',
       'race_class_normalised_Novice', 'race_class_normalised_Selling',
       'race_class_normalised_nan', 'life_days', 'current_age'],
      dtype='object')

# testing data

In [224]:
X_test = df.loc[(df['date'] > '2023-01-01')]

In [225]:
y_test_tmp = df.loc[(df['date'] > '2023-01-01')]

In [226]:
y_test = y_test_tmp['win_or_lose']

In [227]:
X_test = X_test.drop(['win_or_lose', 'date', 'birth_date'], axis = 1)

In [184]:
filtered_df

,meeting_id,date,event_number,distance,distance_raw_furlongs,total_prize_money,track_type,barrier,number,finish_position,...,race_class_normalised_Group 3,race_class_normalised_Handicap,race_class_normalised_Listed,race_class_normalised_Maiden,race_class_normalised_NHF,race_class_normalised_Novice,race_class_normalised_Selling,race_class_normalised_nan,life_days,current_age
0,3668,2020-07-20,1,1100,5.0,4231,1,8,1,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1269,5
1,3668,2020-07-20,7,1760,8.0,4231,1,6,4,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1600,4
2,3668,2020-07-20,7,1760,8.0,4231,1,4,3,7.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3433,4
3,3668,2020-07-20,7,1760,8.0,4231,1,7,2,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1576,3
4,3668,2020-07-20,7,1760,8.0,4231,1,2,1,8.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1617,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173619,35175,2022-12-31,5,1321,6.0,13771,0,3,7,12.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1383,9
173620,35175,2022-12-31,4,2640,12.0,6787,0,8,6,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1421,10
173621,35175,2022-12-31,4,2640,12.0,6787,0,10,5,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2803,8
173622,35175,2022-12-31,4,2640,12.0,6787,0,5,4,7.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1693,7
173623,35175,2022-12-31,5,1321,6.0,13771,0,8,5,10.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1427,11

In [229]:
len(X_train)*.2

34724.8

In [67]:
# type(df['date'])

pandas.core.series.Series

In [68]:
# df_filtered = filtered_df.drop(columns='Unnamed: 0')

In [16]:
# df_filtered.dtypes

meeting_id                         int64
date                              object
event_number                       int64
distance                           int64
distance_raw_furlongs            float64
                                  ...
race_class_normalised_Novice     float64
race_class_normalised_Selling    float64
race_class_normalised_nan        float64
life_days                          int64
current_age                        int64
Length: 67, dtype: object

In [85]:
object_info = df.select_dtypes(include = 'object')

In [86]:
object_info.head(5)

         date  birth_date
0  2020-07-20  2017-01-28
1  2020-07-20  2016-03-03
2  2020-07-20  2011-02-25
3  2020-07-20  2016-03-27
4  2020-07-20  2016-02-15

In [87]:
#drop unnamed column as it's a replica of the index 
df = df.drop(['date', 'birth_date'], axis = 1)

In [88]:
df.columns

Index(['meeting_id', 'event_number', 'distance', 'distance_raw_furlongs',
       'total_prize_money', 'track_type', 'barrier', 'number',
       'finish_position', 'win_or_lose', 'failed_to_finish_reason', 'margin',
       'gear', 'jockey_allowance', 'handicap_weight', 'jockey_id', 'tainer_id',
       'dslr', 'horse_id', 'age', 'official rating', 'wfa',
       'weight_adjustment', 'betfair_starting_price',
       'pre_race_master_rating_int', 'starting_price', 'track_condition_FAST',
       'track_condition_FIRM', 'track_condition_GOOD',
       'track_condition_GOOD TO FIRM', 'track_condition_GOOD TO SOFT',
       'track_condition_GOOD TO YIELDING', 'track_condition_HEAVY',
       'track_condition_SLOW', 'track_condition_SOFT',
       'track_condition_STANDARD', 'track_condition_STANDARD TO FAST',
       'track_condition_STANDARD TO SLOW', 'race_type_FLAT',
       'race_type_NATIONAL_HUNT_FLAT', 'race_class_1', 'race_class_2',
       'race_class_3', 'race_class_4', 'race_class_5', 'race_class_6',
       'race_class_7', 'race_class_normalised_Claiming',
       'race_class_normalised_Conditions', 'race_class_normalised_Grade 1',
       'race_class_normalised_Grade 2', 'race_class_normalised_Group 1',
       'race_class_normalised_Group 2', 'race_class_normalised_Group 3',
       'race_class_normalised_Handicap', 'race_class_normalised_Listed',
       'race_class_normalised_Maiden', 'race_class_normalised_NHF',
       'race_class_normalised_Novice', 'race_class_normalised_Selling',
       'race_class_normalised_nan', 'life_days', 'current_age'],
      dtype='object')

In [89]:
y = df.copy()[['win_or_lose']]

In [90]:
X = df.copy().drop(columns='win_or_lose')

In [34]:
# X_test = X.loc[(df['date'] > '2023-01-01')]

In [35]:
# X_train = X.loc[(df['date'] < '2023-01-01')]

In [36]:
# y_test = y.loc[(df['date'] > '2023-01-01')]

In [37]:
# y_train = y.loc[(df['date'] > '2023-01-01')]

In [91]:
X.shape, y.shape

((207214, 62), (207214, 1))

In [92]:
X.head(5)

,meeting_id,event_number,distance,distance_raw_furlongs,total_prize_money,track_type,barrier,number,finish_position,failed_to_finish_reason,...,race_class_normalised_Group 3,race_class_normalised_Handicap,race_class_normalised_Listed,race_class_normalised_Maiden,race_class_normalised_NHF,race_class_normalised_Novice,race_class_normalised_Selling,race_class_normalised_nan,life_days,current_age
0,3668,1,1100,5.0,4231,1,8,1,2.0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1269,5
1,3668,7,1760,8.0,4231,1,6,4,2.0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1600,4
2,3668,7,1760,8.0,4231,1,4,3,7.0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3433,4
3,3668,7,1760,8.0,4231,1,7,2,1.0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1576,3
4,3668,7,1760,8.0,4231,1,2,1,8.0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1617,5

In [20]:
pd.DataFrame(X).describe()

,meeting_id,event_number,distance,distance_raw_furlongs,total_prize_money,track_type,barrier,number,finish_position,failed_to_finish_reason,margin,gear,jockey_allowance,handicap_weight,jockey_id,tainer_id,dslr,horse_id,age,official rating,wfa,weight_adjustment,betfair_starting_price,pre_race_master_rating_int,starting_price,track_condition_FAST,track_condition_FIRM,track_condition_GOOD,track_condition_GOOD TO FIRM,track_condition_GOOD TO SOFT,track_condition_GOOD TO YIELDING,track_condition_HEAVY,track_condition_SLOW,track_condition_SOFT,track_condition_STANDARD,track_condition_STANDARD TO FAST,track_condition_STANDARD TO SLOW,race_type_FLAT,race_type_NATIONAL_HUNT_FLAT,race_class_1,race_class_2,race_class_3,race_class_4,race_class_5,race_class_6,race_class_7,race_class_normalised_Claiming,race_class_normalised_Conditions,race_class_normalised_Grade 1,race_class_normalised_Grade 2,race_class_normalised_Group 1,race_class_normalised_Group 2,race_class_normalised_Group 3,race_class_normalised_Handicap,race_class_normalised_Listed,race_class_normalised_Maiden,race_class_normalised_NHF,race_class_normalised_Novice,race_class_normalised_Selling,race_class_normalised_nan,life_days,current_age
count,207214.000000,207214.000000,207214.000000,207214.000000,2.072140e+05,207214.000000,207214.000000,207214.00000,206551.000000,207214.000000,207100.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.0,207214.000000,207214.000000,207214.00000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000,207214.0,207214.000000,207214.000000,207214.000000,207214.000000,207214.000000
mean,22397.423630,4.498745,1833.129277,8.333593,1.866630e+04,0.579034,6.007364,6.01346,5.578278,0.003214,219.564409,0.323101,1.034669,129.424696,2759.783523,3830.037801,41.331218,81625.927211,4.447262,69.422925,0.806895,10.590978,30.295012,80.986883,17.616463,0.000058,0.006959,0.197955,0.186223,0.091167,0.000058,0.016736,0.0,0.079937,0.292244,0.00015,0.128514,0.999440,0.000560,0.046479,0.089603,0.080569,0.168700,0.248144,0.363552,0.002953,0.005289,0.006988,0.000203,0.000357,0.007668,0.006853,0.011703,0.900615,0.019839,0.011833,0.0,0.018305,0.008590,0.001757,1735.877397,4.887464
std,11988.959196,2.204079,624.827147,2.839682,5.824295e+04,0.493715,3.825915,3.81768,3.552624,0.056602,626.478012,0.467662,2.077709,6.390837,1668.480520,931.069005,56.656160,53781.479746,2.407116,15.836862,2.391814,6.360749,69.092751,17.034989,23.595218,0.007610,0.083130,0.398459,0.389287,0.287847,0.007610,0.128282,0.0,0.271196,0.454795,0.01223,0.334663,0.023654,0.023654,0.210520,0.285613,0.272173,0.374488,0.431937,0.481023,0.054266,0.072535,0.083302,0.014235,0.018894,0.087233,0.082498,0.107545,0.299179,0.139449,0.108135,0.0,0.134051,0.092284,0.041876,871.609282,3.068361
min,3668.000000,1.000000,1094.000000,5.000000,0.000000e+00,0.000000,1.000000,1.00000,1.000000,0.000000,0.000000,0.000000,0.000000,105.000000,2.000000,1580.000000,1.000000,43.000000,2.000000,11.000000,0.000000,-28.000000,1.019670,3.000000,1.015152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,777.000000,0.000000
25%,9078.000000,3.000000,1321.000000,6.000000,5.311000e+03,0.000000,3.000000,3.00000,3.000000,0.000000,3.000000,0.000000,0.000000,126.000000,1183.000000,3539.000000,14.000000,43609.000000,3.000000,57.000000,0.000000,7.000000,6.535144,69.000000,5.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1239.000000,3.000000
50%,27776.000000,5.000000,1752.000000,8.000000,6.862000e+03,1.000000,5.000000,5.00000,5.000000,0.000000,6.500000,0.000000,0.000000,130.000000,2923.000000,3771.000000,21.000000,65072.000000,4.000000,68.000000,0.000000,10.000000,12.193277,80.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1565.000000,5.000000
75%,33493.500000,6.000000,2200.000000,10.000000,1.104200e+04,1.000000,8.000000,8.00000,8.000000,0.000000,13.750000,1.000000,0.000000,133.000000,3987.000000,3985.000000,36.000000,81127.000000,5.000000,80.000000,0.000000,14.000000,26.000000,92.000000,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,2031.000000,7.000000
max,37996.000000,10.000000,4763.000000,21.600000,1.598514e+06,1.000000,37.000000,37.00000,34.000000,1.000000,4763.000000,1.000000,10.000000,168.000000,9840.000000,8170.000000,364.000000,214775.000000,122.000000,135.000000,25.000000,35.000000,1000.000000,169.000000,501.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,44847.000000,12.000000

In [ ]:
#remove novice races - remove horse races look at where race class normalized is handicapped

In [99]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.3, random_state= 42)

In [114]:
print(f"X_train.shape = {X_train.shape}")
print(f"y_train.shape = {y_train.shape}")
print(f"X_val.shape = {X_val.shape}")
print(f"y_val.shape = {y_val.shape}")
print(f"X_test.shape = {X_test.shape}")
print(f"y_test.shape = {y_test.shape}")

X_train.shape = (101534, 62)
y_train.shape = (101534, 1)
X_val.shape = (43515, 62)
y_val.shape = (43515, 1)
X_test.shape = (62165, 62)
y_test.shape = (62165, 1)

In [111]:
metrics = [
    keras.metrics.Recall(name='recall'),
    keras.metrics.Precision(name='precision'),
    keras.metrics.AUC(name='prc', curve='PR'),  # precision-recall curve
]

2024-03-07 16:19:51.596507: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-03-07 16:19:51.598402: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2024-03-07 16:19:51.599765: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Tomz-PC): /proc/driver/nvidia/version does not exist
2024-03-07 16:19:51.616344: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [141]:
es = EarlyStopping(patience=4),

In [142]:
def inititialize_model():
   
    #architecture
#     normaliser = Normalization() commented as already have normalizing method applied as part of pipeline
    model = models.Sequential()
    model.add(layers.Dense(1000, activation = 'relu', input_dim=X_train.shape[-1]))
    model.add(layers.Dropout(rate=0.2))
    model.add(layers.Dense(500, activation = 'relu'))
    model.add(layers.Dropout(rate=0.2))
    model.add(layers.Dense(100, activation = 'relu'))
    model.add(layers.Dropout(rate=0.2))
    model.add(layers.Dense(1, activation = 'sigmoid'))
    
    # classification comilation
    optimizer = Adam(lr=0.0001)
    model.compile(loss='categorical_crossentropy',
              optimizer=optimizer, 
              metrics=['accuracy', 'precision'])
    return model

In [143]:
model = inititialize_model()

In [146]:
X_val.shape

(43515, 62)

In [148]:
history = model.fit(X_train, y_train,
                    validation_data=(X_val, y_val),
                    epochs=100,
                    batch_size=64, # Large enough to get a decent chance of containing fraudulent transactions 
                    callbacks=[es], shuffle=True)

Epoch 1/100

ValueError: in user code:

    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/engine/training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/engine/training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/engine/training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/engine/training.py", line 994, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/engine/training.py", line 1052, in compute_loss
        return self.compiled_loss(
    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/losses.py", line 152, in __call__
        losses = call_fn(y_true, y_pred)
    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/losses.py", line 272, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/losses.py", line 1990, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "/home/tomi/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/keras/backend.py", line 5529, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 1) and (None, 50) are incompatible

In [ ]:
    
    #fit model
    model.fit(X_train, y_train, batch_size=32, epochs=100)