In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from datetime import datetime

In [2]:
!pwd

/Users/jubba/which_horse/notebook

In [3]:
file_csv = '/Users/jubba/Downloads/combined_jump_csv.csv'

In [4]:
df_jump = pd.read_csv(file_csv, dtype = {
                                        'race_type' : str,
                                        'dslr' : float,
                                        'run_3_track_type' : str,
                                        })

df_jump

/var/folders/y1/7l27jzt92cs7ljtj5xn5sd3h0000gn/T/ipykernel_49492/3640737931.py:1: DtypeWarning: Columns (9,22,53,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df_jump = pd.read_csv(file_csv, dtype = {

,meeting_id,meeting_name,date,country_code,event_number,distance,distance_unit,distance_furlongs,distance_raw_furlongs,race_class,...,run_7_dsr,run_8_raw_post_race_rating_int,run_8_raw_post_race_rating_symbol,run_8_final_rating_int,run_8_race_type,run_8_race_class,run_8_race_class_normalised,run_8_track_type,run_8_win_lose,run_8_dsr
0,3671,MARKET RASEN,2020-07-20,GBR,1,3645,yards,2m0.5f,16.6,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3671,MARKET RASEN,2020-07-20,GBR,4,5251,yards,2m8f,23.9,3,...,440.0,113.0,NaN,118.0,JUMP,3,Handicap,TURF,0.0,454.0
2,3671,MARKET RASEN,2020-07-20,GBR,4,5251,yards,2m8f,23.9,3,...,1161.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3671,MARKET RASEN,2020-07-20,GBR,4,5251,yards,2m8f,23.9,3,...,605.0,NaN,NaN,NaN,STEEPLECHASE,3,Handicap,TURF,1.0,781.0
4,3671,MARKET RASEN,2020-07-20,GBR,4,5251,yards,2m8f,23.9,3,...,454.0,NaN,NaN,NaN,STEEPLECHASE,4,Handicap,TURF,0.0,627.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127627,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,557.0,106.0,NaN,108.0,STEEPLECHASE,4,Novice,TURF,0.0,581.0
127628,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,336.0,122.0,+,129.0,JUMP,4,Handicap,TURF,1.0,511.0
127629,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,134.0,121.0,NaN,130.0,STEEPLECHASE,3,Handicap,TURF,0.0,155.0
127630,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,296.0,NaN,NaN,NaN,JUMP,3,Handicap,TURF,0.0,310.0
127631,37980,MARKET RASEN,2023-09-30,GBR,7,4100,yards,2m2.5f,18.6,5,...,260.0,85.0,NaN,106.0,JUMP,5,Handicap,TURF,0.0,296.0

In [5]:
df_columns = list(df_jump.columns)
df_columns

['meeting_id',
 'meeting_name',
 'date',
 'country_code',
 'event_number',
 'distance',
 'distance_unit',
 'distance_furlongs',
 'distance_raw_furlongs',
 'race_class',
 'race_class_normalised',
 'prize_money_currency',
 'total_prize_money',
 'track_condition',
 'race_type',
 'track_type',
 'barrier',
 'number',
 'finish_position',
 'win_or_lose',
 'failed_to_finish_reason',
 'margin',
 'gear',
 'jockey_allowance',
 'jockey_allowance_unit',
 'handicap_weight',
 'handicap_weight_unit',
 'jockey_id',
 'jockey_name',
 'tainer_id',
 'trainer_name',
 'dslr',
 'horse_id',
 'horse_name',
 'sire',
 'dam',
 'age',
 'birth_date',
 'official rating',
 'wfa',
 'weight_adjustment',
 'bet365_odds',
 'pmu_odds',
 'betfair_starting_price',
 'pre_race_master_rating_int',
 'pre_race_master_rating_symbol',
 'post_race_master_rating_int',
 'post_race_master_rating_symbol',
 'starting_price',
 'run_1_raw_post_race_rating_int',
 'run_1_raw_post_race_rating_symbol',
 'run_1_final_rating_int',
 'run_1_race_type',
 'run_1_race_class_normalised',
 'run_1_race_class',
 'run_1_track_type',
 'run_1_win_lose',
 'run_1_dsr',
 'run_2_raw_post_race_rating_int',
 'run_2_raw_post_race_rating_symbol',
 'run_2_final_rating_int',
 'run_2_race_type',
 'run_2_race_class',
 'run_2_race_class_normalised',
 'run_2_track_type',
 'run_2_win_lose',
 'run_2_dsr',
 'run_3_raw_post_race_rating_int',
 'run_3_raw_post_race_rating_symbol',
 'run_3_final_rating_int',
 'run_3_race_type',
 'run_3_race_class',
 'run_3_race_class_normalised',
 'run_3_track_type',
 'run_3_win_lose',
 'run_3_dsr',
 'run_4_raw_post_race_rating_int',
 'run_4_raw_post_race_rating_symbol',
 'run_4_final_rating_int',
 'run_4_race_type',
 'run_4_race_class',
 'run_4_race_class_normalised',
 'run_4_track_type',
 'run_4_win_lose',
 'run_4_dsr',
 'run_5_raw_post_race_rating_int',
 'run_5_raw_post_race_rating_symbol',
 'run_5_final_rating_int',
 'run_5_race_type',
 'run_5_race_class',
 'run_5_race_class_normalised',
 'run_5_track_type',
 'run_5_win_lose',
 'run_5_dsr',
 'run_6_raw_post_race_rating_int',
 'run_6_raw_post_race_rating_symbol',
 'run_6_final_rating_int',
 'run_6_race_type',
 'run_6_race_class',
 'run_6_race_class_normalised',
 'run_6_track_type',
 'run_6_win_lose',
 'run_6_dsr',
 'run_7_raw_post_race_rating_int',
 'run_7_raw_post_race_rating_symbol',
 'run_7_final_rating_int',
 'run_7_race_type',
 'run_7_race_class',
 'run_7_race_class_normalised',
 'run_7_track_type',
 'run_7_win_lose',
 'run_7_dsr',
 'run_8_raw_post_race_rating_int',
 'run_8_raw_post_race_rating_symbol',
 'run_8_final_rating_int',
 'run_8_race_type',
 'run_8_race_class',
 'run_8_race_class_normalised',
 'run_8_track_type',
 'run_8_win_lose',
 'run_8_dsr']

In [6]:
df_jump['race_type'].unique()

array(['JUMP', 'STEEPLECHASE', 'CROSS_COUNTRY'], dtype=object)

In [7]:
df_jump.describe()

,meeting_id,event_number,distance,distance_raw_furlongs,total_prize_money,barrier,number,finish_position,win_or_lose,margin,...,run_6_win_lose,run_6_dsr,run_7_raw_post_race_rating_int,run_7_final_rating_int,run_7_win_lose,run_7_dsr,run_8_raw_post_race_rating_int,run_8_final_rating_int,run_8_win_lose,run_8_dsr
count,127632.000000,127632.000000,127632.000000,127632.000000,127632.000000,127632.000000,127632.000000,106080.00000,127632.000000,90747.000000,...,97194.000000,97194.000000,52565.000000,52565.000000,91341.000000,91341.000000,47168.000000,47168.000000,85682.000000,85682.000000
mean,22143.051178,3.867698,4426.600351,20.121581,15628.120166,5.708592,5.708576,4.55789,0.120369,24.562007,...,0.141331,417.458681,88.005631,99.507562,0.141552,478.003799,87.535723,99.046875,0.143823,536.765377
std,11654.526056,1.988520,768.465412,3.492690,37346.828396,3.775582,3.775591,2.96286,0.325316,22.441424,...,0.348242,252.585678,27.826154,26.674512,0.348470,267.841985,27.881982,26.749707,0.350787,281.944659
min,3671.000000,1.000000,1110.000000,5.000000,1635.000000,1.000000,1.000000,1.00000,0.000000,0.000000,...,0.000000,44.000000,25.000000,13.000000,0.000000,51.000000,25.000000,21.000000,0.000000,63.000000
25%,9101.000000,2.000000,3645.000000,16.600000,6000.000000,3.000000,3.000000,2.00000,0.000000,8.000000,...,0.000000,258.000000,66.000000,80.000000,0.000000,312.000000,65.000000,80.000000,0.000000,355.000000
50%,26816.000000,4.000000,4400.000000,20.000000,7672.000000,5.000000,5.000000,4.00000,0.000000,18.500000,...,0.000000,365.000000,89.000000,100.000000,0.000000,412.000000,88.000000,100.000000,0.000000,464.000000
75%,32879.000000,6.000000,5076.000000,23.100000,11214.000000,8.000000,8.000000,6.00000,0.000000,34.750000,...,0.000000,493.000000,109.000000,119.000000,0.000000,598.000000,109.000000,118.000000,0.000000,674.000000
max,37980.000000,10.000000,7554.000000,34.300000,865000.000000,40.000000,40.000000,24.00000,1.000000,263.750000,...,1.000000,3371.000000,175.000000,183.000000,1.000000,3359.000000,173.000000,184.000000,1.000000,3382.000000

**JUMPER**

In [8]:
df_jump = df_jump.drop(columns=['run_6_raw_post_race_rating_int',
 'run_6_raw_post_race_rating_symbol',
 'run_6_final_rating_int',
 'run_6_race_type',
 'run_6_race_class',
 'run_6_race_class_normalised',
 'run_6_track_type',
 'run_6_win_lose',
 'run_6_dsr',
 'run_7_raw_post_race_rating_int',
 'run_7_raw_post_race_rating_symbol',
 'run_7_final_rating_int',
 'run_7_race_type',
 'run_7_race_class',
 'run_7_race_class_normalised',
 'run_7_track_type',
 'run_7_win_lose',
 'run_7_dsr',
 'run_8_raw_post_race_rating_int',
 'run_8_raw_post_race_rating_symbol',
 'run_8_final_rating_int',
 'run_8_race_type',
 'run_8_race_class',
 'run_8_race_class_normalised',
 'run_8_track_type',
 'run_8_win_lose',
 'run_8_dsr',
 'sire',
 'dam'])
#races from 6 7 8 droped master rating on cureent race
#only applicable to previous 5 races or races in the last 365 days
#sire and dam are not of much significance

In [9]:
df_jump['date']

0         2020-07-20
1         2020-07-20
2         2020-07-20
3         2020-07-20
4         2020-07-20
             ...
127627    2023-09-30
127628    2023-09-30
127629    2023-09-30
127630    2023-09-30
127631    2023-09-30
Name: date, Length: 127632, dtype: object

In [10]:
df_jump['date'] = pd.to_datetime(df_jump['date'])

In [11]:
df_jump['year'] = df_jump['date'].dt.year

In [12]:
df_jump

,meeting_id,meeting_name,date,country_code,event_number,distance,distance_unit,distance_furlongs,distance_raw_furlongs,race_class,...,run_5_raw_post_race_rating_int,run_5_raw_post_race_rating_symbol,run_5_final_rating_int,run_5_race_type,run_5_race_class,run_5_race_class_normalised,run_5_track_type,run_5_win_lose,run_5_dsr,year
0,3671,MARKET RASEN,2020-07-20,GBR,1,3645,yards,2m0.5f,16.6,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
1,3671,MARKET RASEN,2020-07-20,GBR,4,5251,yards,2m8f,23.9,3,...,105.0,NaN,110.0,JUMP,3,Handicap,TURF,0.0,365.0,2020
2,3671,MARKET RASEN,2020-07-20,GBR,4,5251,yards,2m8f,23.9,3,...,111.0,NaN,124.0,JUMP,4,Novice,TURF,0.0,820.0,2020
3,3671,MARKET RASEN,2020-07-20,GBR,4,5251,yards,2m8f,23.9,3,...,NaN,NaN,NaN,STEEPLECHASE,3,Handicap,TURF,0.0,532.0,2020
4,3671,MARKET RASEN,2020-07-20,GBR,4,5251,yards,2m8f,23.9,3,...,NaN,NaN,NaN,STEEPLECHASE,3,Handicap,TURF,0.0,414.0,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127627,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,131.0,NaN,133.0,STEEPLECHASE,3.0,Handicap,TURF,1.0,504.0,2023
127628,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,117.0,NaN,124.0,JUMP,4.0,Handicap,TURF,0.0,245.0,2023
127629,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,128.0,NaN,137.0,STEEPLECHASE,3.0,Handicap,TURF,1.0,98.0,2023
127630,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,131.0,?,143.0,JUMP,4.0,Handicap,TURF,1.0,220.0,2023
127631,37980,MARKET RASEN,2023-09-30,GBR,7,4100,yards,2m2.5f,18.6,5,...,70.0,NaN,91.0,JUMP,2.0,Handicap,TURF,0.0,190.0,2023

In [13]:
df_jump['year'].unique()

array([2020, 2019, 2021, 2022, 2023], dtype=int32)

In [14]:
mask2019 = df_jump['year'] == 2019
df_jump_2019 = df_jump[mask2019]
df_jump_2019
mask2020 = df_jump['year'] == 2020
df_jump_2020 = df_jump[mask2020]
df_jump_2020
mask2021 = df_jump['year'] == 2021
df_jump_2021 = df_jump[mask2021]
df_jump_2021
mask2022 = df_jump['year'] == 2022
df_jump_2022 = df_jump[mask2022]
df_jump_2022
mask2023 = df_jump['year'] == 2023
df_jump_2023 = df_jump[mask2023]
df_jump_2023

#dataframes seperated by year

,meeting_id,meeting_name,date,country_code,event_number,distance,distance_unit,distance_furlongs,distance_raw_furlongs,race_class,...,run_5_raw_post_race_rating_int,run_5_raw_post_race_rating_symbol,run_5_final_rating_int,run_5_race_type,run_5_race_class,run_5_race_class_normalised,run_5_track_type,run_5_win_lose,run_5_dsr,year
108941,35179,CHELTENHAM,2023-01-01,GBR,4,4527,yards,2m4.5f,20.6,1,...,NaN,NaN,NaN,JUMP,NaN,NaN,TURF,0.0,265.0,2023
108942,35179,CHELTENHAM,2023-01-01,GBR,4,4527,yards,2m4.5f,20.6,1,...,NaN,NaN,NaN,STEEPLECHASE,3,Handicap,TURF,0.0,309.0,2023
108943,35179,CHELTENHAM,2023-01-01,GBR,5,4456,yards,2m4.5f,20.3,1,...,138.0,NaN,146.0,JUMP,2,Handicap,TURF,0.0,387.0,2023
108944,35179,CHELTENHAM,2023-01-01,GBR,4,4527,yards,2m4.5f,20.6,1,...,139.0,+,162.0,STEEPLECHASE,4,Novice,TURF,0.0,683.0,2023
108945,35179,CHELTENHAM,2023-01-01,GBR,4,4527,yards,2m4.5f,20.6,1,...,134.0,NaN,157.0,STEEPLECHASE,1,Grade 2,TURF,0.0,274.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127627,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,131.0,NaN,133.0,STEEPLECHASE,3.0,Handicap,TURF,1.0,504.0,2023
127628,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,117.0,NaN,124.0,JUMP,4.0,Handicap,TURF,0.0,245.0,2023
127629,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,128.0,NaN,137.0,STEEPLECHASE,3.0,Handicap,TURF,1.0,98.0,2023
127630,37980,MARKET RASEN,2023-09-30,GBR,4,4709,yards,2m5.5f,21.4,3,...,131.0,?,143.0,JUMP,4.0,Handicap,TURF,1.0,220.0,2023
127631,37980,MARKET RASEN,2023-09-30,GBR,7,4100,yards,2m2.5f,18.6,5,...,70.0,NaN,91.0,JUMP,2.0,Handicap,TURF,0.0,190.0,2023

In [15]:
len(df_jump.columns)

93

In [16]:
#print(df_jump.nunique() < 2)
columns_true_to_condition = df_jump.nunique()[df_jump.nunique() < 2].index
columns_true_to_condition

Index(['country_code', 'distance_unit', 'prize_money_currency',
       'jockey_allowance_unit', 'handicap_weight_unit', 'pmu_odds'],
      dtype='object')

In [17]:
df_jump = df_jump.drop(columns=['country_code', 'distance_unit', 'prize_money_currency',
       'jockey_allowance_unit', 'handicap_weight_unit', 'pmu_odds', 'year'])

In [18]:
df_columns_flat = ['meeting_id', 'date', 'event_number', 'distance',
       'distance_raw_furlongs', 'race_class_normalised', 'total_prize_money',
       'track_condition', 'race_type', 'track_type', 'barrier', 'number',
       'finish_position', 'win_or_lose', 'failed_to_finish_reason', 'margin',
       'gear', 'jockey_allowance', 'handicap_weight', 'jockey_id', 'tainer_id',
       'dslr', 'horse_id', 'sire', 'dam', 'age', 'birth_date',
       'official rating', 'wfa', 'weight_adjustment', 'betfair_starting_price',
       'pre_race_master_rating_int', 'post_race_master_rating_int',
       'starting_price', 'run_1_raw_post_race_rating_int',
       'run_1_final_rating_int', 'run_1_race_type', 'run_1_race_class',
       'run_1_track_type', 'run_1_win_lose', 'run_1_dsr',
       'run_2_raw_post_race_rating_int', 'run_2_final_rating_int',
       'run_2_race_type', 'run_2_race_class_normalised', 'run_2_track_type',
       'run_2_win_lose', 'run_2_dsr', 'run_3_raw_post_race_rating_int',
       'run_3_final_rating_int', 'run_3_race_type',
       'run_3_race_class_normalised', 'run_3_track_type', 'run_3_win_lose',
       'run_3_dsr', 'run_4_raw_post_race_rating_int', 'run_4_final_rating_int',
       'run_4_race_type', 'run_4_race_class_normalised', 'run_4_track_type',
       'run_4_win_lose', 'run_4_dsr', 'run_5_raw_post_race_rating_int',
       'run_5_final_rating_int', 'run_5_race_type',
       'run_5_race_class_normalised', 'run_5_track_type', 'run_5_win_lose',
       'run_5_dsr', 'dam_id', 'sire_id']

##########
FLAT COLUMN FEATURES
##########

In [19]:
len(df_columns_flat)

71

##########
JUMP COLUMN FEATTURES 
##########

In [20]:
len(df_jump.columns)

86

In [21]:
#columns_to_keep = [col for col in df_columns_flat if col in df_jump.columns]
#df_jump = df_jump[columns_to_keep]
#code that willo make me and amanda have thesame features

In [22]:
df_jump.columns

Index(['meeting_id', 'meeting_name', 'date', 'event_number', 'distance',
       'distance_furlongs', 'distance_raw_furlongs', 'race_class',
       'race_class_normalised', 'total_prize_money', 'track_condition',
       'race_type', 'track_type', 'barrier', 'number', 'finish_position',
       'win_or_lose', 'failed_to_finish_reason', 'margin', 'gear',
       'jockey_allowance', 'handicap_weight', 'jockey_id', 'jockey_name',
       'tainer_id', 'trainer_name', 'dslr', 'horse_id', 'horse_name', 'age',
       'birth_date', 'official rating', 'wfa', 'weight_adjustment',
       'bet365_odds', 'betfair_starting_price', 'pre_race_master_rating_int',
       'pre_race_master_rating_symbol', 'post_race_master_rating_int',
       'post_race_master_rating_symbol', 'starting_price',
       'run_1_raw_post_race_rating_int', 'run_1_raw_post_race_rating_symbol',
       'run_1_final_rating_int', 'run_1_race_type',
       'run_1_race_class_normalised', 'run_1_race_class', 'run_1_track_type',
       'run_1_win_lose', 'run_1_dsr', 'run_2_raw_post_race_rating_int',
       'run_2_raw_post_race_rating_symbol', 'run_2_final_rating_int',
       'run_2_race_type', 'run_2_race_class', 'run_2_race_class_normalised',
       'run_2_track_type', 'run_2_win_lose', 'run_2_dsr',
       'run_3_raw_post_race_rating_int', 'run_3_raw_post_race_rating_symbol',
       'run_3_final_rating_int', 'run_3_race_type', 'run_3_race_class',
       'run_3_race_class_normalised', 'run_3_track_type', 'run_3_win_lose',
       'run_3_dsr', 'run_4_raw_post_race_rating_int',
       'run_4_raw_post_race_rating_symbol', 'run_4_final_rating_int',
       'run_4_race_type', 'run_4_race_class', 'run_4_race_class_normalised',
       'run_4_track_type', 'run_4_win_lose', 'run_4_dsr',
       'run_5_raw_post_race_rating_int', 'run_5_raw_post_race_rating_symbol',
       'run_5_final_rating_int', 'run_5_race_type', 'run_5_race_class',
       'run_5_race_class_normalised', 'run_5_track_type', 'run_5_win_lose',
       'run_5_dsr'],
      dtype='object')

In [23]:
df_jump.dtypes

meeting_id                              int64
meeting_name                           object
date                           datetime64[ns]
event_number                            int64
distance                                int64
                                    ...
run_5_race_class                       object
run_5_race_class_normalised            object
run_5_track_type                       object
run_5_win_lose                        float64
run_5_dsr                             float64
Length: 86, dtype: object

In [24]:
df_jump['distance'].nunique()

#158 differentrce distances

334

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [26]:
#6 Different Data Frames
#1 with all jump race data
#5 which are segregated by year fron 2019-2023
jump_dataframes = [df_jump.head(), df_jump_2019.head(), df_jump_2020.head(), df_jump_2021.head(), df_jump_2022.head(), df_jump_2023.head()]
jump_dataframes

[   meeting_id  meeting_name       date  event_number  distance  \
 0        3671  MARKET RASEN 2020-07-20             1      3645
 1        3671  MARKET RASEN 2020-07-20             4      5251
 2        3671  MARKET RASEN 2020-07-20             4      5251
 3        3671  MARKET RASEN 2020-07-20             4      5251
 4        3671  MARKET RASEN 2020-07-20             4      5251

   distance_furlongs  distance_raw_furlongs race_class race_class_normalised  \
 0            2m0.5f                   16.6          4                Novice
 1              2m8f                   23.9          3              Handicap
 2              2m8f                   23.9          3              Handicap
 3              2m8f                   23.9          3              Handicap
 4              2m8f                   23.9          3              Handicap

    total_prize_money  ... run_4_dsr run_5_raw_post_race_rating_int  \
 0               5312  ...       NaN                            NaN
 1               9542  ...     327.0                          105.0
 2               9542  ...     801.0                          111.0
 3               9542  ...     484.0                            NaN
 4               9542  ...     383.0                            NaN

   run_5_raw_post_race_rating_symbol  run_5_final_rating_int  run_5_race_type  \
 0                               NaN                     NaN              NaN
 1                               NaN                   110.0             JUMP
 2                               NaN                   124.0             JUMP
 3                               NaN                     NaN     STEEPLECHASE
 4                               NaN                     NaN     STEEPLECHASE

    run_5_race_class  run_5_race_class_normalised run_5_track_type  \
 0               NaN                          NaN              NaN
 1                 3                     Handicap             TURF
 2                 4                       Novice             TURF
 3                 3                     Handicap             TURF
 4                 3                     Handicap             TURF

    run_5_win_lose run_5_dsr
 0             NaN       NaN
 1             0.0     365.0
 2             0.0     820.0
 3             0.0     532.0
 4             0.0     414.0

 [5 rows x 86 columns],
      meeting_id meeting_name       date country_code  event_number  distance  \
 206        7071    CATTERICK 2019-01-01          GBR             2      3456
 207        7071    CATTERICK 2019-01-01          GBR             6      5571
 208        7071    CATTERICK 2019-01-01          GBR             6      5571
 209        7071    CATTERICK 2019-01-01          GBR             2      3456
 210        7071    CATTERICK 2019-01-01          GBR             2      3456

     distance_unit distance_furlongs  distance_raw_furlongs race_class  ...  \
 206         yards            1m7.5f                   15.7          4  ...
 207         yards            3m1.5f                   25.3          5  ...
 208         yards            3m1.5f                   25.3          5  ...
 209         yards            1m7.5f                   15.7          4  ...
 210         yards            1m7.5f                   15.7          4  ...

     run_5_raw_post_race_rating_int run_5_raw_post_race_rating_symbol  \
 206                            NaN                               NaN
 207                            NaN                               NaN
 208                            NaN                               NaN
 209                            NaN                               NaN
 210                           69.0                               NaN

      run_5_final_rating_int run_5_race_type run_5_race_class  \
 206                     NaN            JUMP                4
 207                     NaN    STEEPLECHASE                4
 208                     NaN            JUMP                4
 209                     NaN            JUMP                5
 210                    77.0            FLAT                4

     run_5_race_class_normalised  run_5_track_type  run_5_win_lose  run_5_dsr  \
 206                    Handicap              TURF             0.0      295.0
 207                    Handicap              TURF             0.0       64.0
 208                    Handicap              TURF             0.0       86.0
 209                      Novice              TURF             0.0      299.0
 210                    Handicap              TURF             0.0      208.0

      year
 206  2019
 207  2019
 208  2019
 209  2019
 210  2019

 [5 rows x 93 columns],
    meeting_id  meeting_name       date country_code  event_number  distance  \
 0        3671  MARKET RASEN 2020-07-20          GBR             1      3645
 1        3671  MARKET RASEN 2020-07-20          GBR             4      5251
 2        3671  MARKET RASEN 2020-07-20          GBR             4      5251
 3        3671  MARKET RASEN 2020-07-20          GBR             4      5251
 4        3671  MARKET RASEN 2020-07-20          GBR             4      5251

   distance_unit distance_furlongs  distance_raw_furlongs race_class  ...  \
 0         yards            2m0.5f                   16.6          4  ...
 1         yards              2m8f                   23.9          3  ...
 2         yards              2m8f                   23.9          3  ...
 3         yards              2m8f                   23.9          3  ...
 4         yards              2m8f                   23.9          3  ...

   run_5_raw_post_race_rating_int run_5_raw_post_race_rating_symbol  \
 0                            NaN                               NaN
 1                          105.0                               NaN
 2                          111.0                               NaN
 3                            NaN                               NaN
 4                            NaN                               NaN

    run_5_final_rating_int run_5_race_type run_5_race_class  \
 0                     NaN             NaN              NaN
 1                   110.0            JUMP                3
 2                   124.0            JUMP                4
 3                     NaN    STEEPLECHASE                3
 4                     NaN    STEEPLECHASE                3

   run_5_race_class_normalised  run_5_track_type  run_5_win_lose  run_5_dsr  \
 0                         NaN               NaN             NaN        NaN
 1                    Handicap              TURF             0.0      365.0
 2                      Novice              TURF             0.0      820.0
 3                    Handicap              TURF             0.0      532.0
 4                    Handicap              TURF             0.0      414.0

    year
 0  2020
 1  2020
 2  2020
 3  2020
 4  2020

 [5 rows x 93 columns],
        meeting_id meeting_name       date country_code  event_number  \
 51954       10991  MUSSELBURGH 2021-01-01          GBR             3
 51955       10991  MUSSELBURGH 2021-01-01          GBR             3
 51956       10991  MUSSELBURGH 2021-01-01          GBR             3
 51957       10991  MUSSELBURGH 2021-01-01          GBR             2
 51958       10991  MUSSELBURGH 2021-01-01          GBR             2

        distance distance_unit distance_furlongs  distance_raw_furlongs  \
 51954      3424         yards            1m7.5f                   15.6
 51955      3424         yards            1m7.5f                   15.6
 51956      3424         yards            1m7.5f                   15.6
 51957      4351         yards              2m4f                   19.8
 51958      4351         yards              2m4f                   19.8

       race_class  ... run_5_raw_post_race_rating_int  \
 51954          2  ...                          122.0
 51955          2  ...                          132.0
 51956          2  ...                            NaN
 51957          3  ...                           83.0
 51958          3  ...                          126.0

       run_5_raw_post_race_rating_symbol  run_5_final_rating_int  \
 51954                               NaN                   132.0
 51955                               NaN                   136.0
 51956                               NaN                     NaN
 51957                                ++                   109.0
 51958                                S+                   134.0

       run_5_race_type run_5_race_class run_5_race_class_normalised  \
 51954            JUMP                2                    Handicap
 51955            JUMP                3                    Handicap
 51956    STEEPLECHASE              NaN                     Grade 2
 51957            FLAT                4                    Handicap
 51958            JUMP                4                      Maiden

        run_5_track_type  run_5_win_lose  run_5_dsr  year
 51954              TURF             0.0      175.0  2021
 51955              TURF             1.0      371.0  2021
 51956              TURF             0.0      348.0  2021
 51957              TURF             1.0      148.0  2021
 51958              TURF             1.0      390.0  2021

 [5 rows x 93 columns],
        meeting_id meeting_name       date country_code  event_number  \
 81423       29619   CHELTENHAM 2022-01-01          GBR             2
 81424       29619   CHELTENHAM 2022-01-01          GBR             4
 81425       29619   CHELTENHAM 2022-01-01          GBR             4
 81426       29619   CHELTENHAM 2022-01-01          GBR             4
 81427       29619   CHELTENHAM 2022-01-01          GBR             4

        distance distance_unit distance_furlongs  distance_raw_furlongs  \
 81423      5790         yards            3m2.5f                   26.3
 81424      4527         yards            2m4.5f                   20.6
 81425      4527         yards            2m4.5f                   20.6
 81426      4527         yards            2m4.5f                   20.6
 81427      4527         yards            2m4.5f                   20.6

       race_class  ... run_5_raw_post_race_rating_int  \
 81423          2  ...                           90.0
 81424          1  ...                          143.0
 81425          1  ...                            NaN
 81426          1  ...                            NaN
 81427          1  ...                          104.0

       run_5_raw_post_race_rating_symbol  run_5_final_rating_int  \
 81423                               NaN                   102.0
 81424                               NaN                   159.0
 81425                               NaN                     NaN
 81426                               NaN                     NaN
 81427                               NaN                   126.0

       run_5_race_type run_5_race_class run_5_race_class_normalised  \
 81423    STEEPLECHASE                1                     Grade 3
 81424    STEEPLECHASE                2                    Handicap
 81425    STEEPLECHASE                1                      Listed
 81426    STEEPLECHASE              NaN                         NaN
 81427    STEEPLECHASE                2                    Handicap

        run_5_track_type  run_5_win_lose  run_5_dsr  year
 81423              TURF             0.0      392.0  2022
 81424              TURF             1.0      280.0  2022
 81425              TURF             1.0      672.0  2022
 81426              TURF             0.0      881.0  2022
 81427              TURF             0.0      310.0  2022

 [5 rows x 93 columns],
         meeting_id meeting_name       date country_code  event_number  \
 108941       35179   CHELTENHAM 2023-01-01          GBR             4
 108942       35179   CHELTENHAM 2023-01-01          GBR             4
 108943       35179   CHELTENHAM 2023-01-01          GBR             5
 108944       35179   CHELTENHAM 2023-01-01          GBR             4
 108945       35179   CHELTENHAM 2023-01-01          GBR             4

         distance distance_unit distance_furlongs  distance_raw_furlongs  \
 108941      4527         yards            2m4.5f                   20.6
 108942      4527         yards            2m4.5f                   20.6
 108943      4456         yards            2m4.5f                   20.3
 108944      4527         yards            2m4.5f                   20.6
 108945      4527         yards            2m4.5f                   20.6

        race_class  ... run_5_raw_post_race_rating_int  \
 108941          1  ...                            NaN
 108942          1  ...                            NaN
 108943          1  ...                          138.0
 108944          1  ...                          139.0
 108945          1  ...                          134.0

        run_5_raw_post_race_rating_symbol  run_5_final_rating_int  \
 108941                               NaN                     NaN
 108942                               NaN                     NaN
 108943                               NaN                   146.0
 108944                                 +                   162.0
 108945                               NaN                   157.0

        run_5_race_type run_5_race_class run_5_race_class_normalised  \
 108941            JUMP              NaN                         NaN
 108942    STEEPLECHASE                3                    Handicap
 108943            JUMP                2                    Handicap
 108944    STEEPLECHASE                4                      Novice
 108945    STEEPLECHASE                1                     Grade 2

         run_5_track_type  run_5_win_lose  run_5_dsr  year
 108941              TURF             0.0      265.0  2023
 108942              TURF             0.0      309.0  2023
 108943              TURF             0.0      387.0  2023
 108944              TURF             0.0      683.0  2023
 108945              TURF             0.0      274.0  2023

 [5 rows x 93 columns]]

In [27]:
df_jump

,meeting_id,meeting_name,date,event_number,distance,distance_furlongs,distance_raw_furlongs,race_class,race_class_normalised,total_prize_money,...,run_4_dsr,run_5_raw_post_race_rating_int,run_5_raw_post_race_rating_symbol,run_5_final_rating_int,run_5_race_type,run_5_race_class,run_5_race_class_normalised,run_5_track_type,run_5_win_lose,run_5_dsr
0,3671,MARKET RASEN,2020-07-20,1,3645,2m0.5f,16.6,4,Novice,5312,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3671,MARKET RASEN,2020-07-20,4,5251,2m8f,23.9,3,Handicap,9542,...,327.0,105.0,NaN,110.0,JUMP,3,Handicap,TURF,0.0,365.0
2,3671,MARKET RASEN,2020-07-20,4,5251,2m8f,23.9,3,Handicap,9542,...,801.0,111.0,NaN,124.0,JUMP,4,Novice,TURF,0.0,820.0
3,3671,MARKET RASEN,2020-07-20,4,5251,2m8f,23.9,3,Handicap,9542,...,484.0,NaN,NaN,NaN,STEEPLECHASE,3,Handicap,TURF,0.0,532.0
4,3671,MARKET RASEN,2020-07-20,4,5251,2m8f,23.9,3,Handicap,9542,...,383.0,NaN,NaN,NaN,STEEPLECHASE,3,Handicap,TURF,0.0,414.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127627,37980,MARKET RASEN,2023-09-30,4,4709,2m5.5f,21.4,3,Handicap,20974,...,372.0,131.0,NaN,133.0,STEEPLECHASE,3.0,Handicap,TURF,1.0,504.0
127628,37980,MARKET RASEN,2023-09-30,4,4709,2m5.5f,21.4,3,Handicap,20974,...,217.0,117.0,NaN,124.0,JUMP,4.0,Handicap,TURF,0.0,245.0
127629,37980,MARKET RASEN,2023-09-30,4,4709,2m5.5f,21.4,3,Handicap,20974,...,70.0,128.0,NaN,137.0,STEEPLECHASE,3.0,Handicap,TURF,1.0,98.0
127630,37980,MARKET RASEN,2023-09-30,4,4709,2m5.5f,21.4,3,Handicap,20974,...,212.0,131.0,?,143.0,JUMP,4.0,Handicap,TURF,1.0,220.0
127631,37980,MARKET RASEN,2023-09-30,7,4100,2m2.5f,18.6,5,Handicap,9534,...,141.0,70.0,NaN,91.0,JUMP,2.0,Handicap,TURF,0.0,190.0

Converting columns with multiple datatypes into 1 data type

In [28]:
print(df_jump.iloc[:,8])
print(df_jump.iloc[:,21])
print(df_jump.iloc[:,52])
#race_type, dslr, run_3_track_type, is where multipledata types are within the same column

0           Novice
1         Handicap
2         Handicap
3         Handicap
4         Handicap
            ...
127627    Handicap
127628    Handicap
127629    Handicap
127630    Handicap
127631    Handicap
Name: race_class_normalised, Length: 127632, dtype: object
0         140.0
1         163.0
2         155.0
3         152.0
4         149.0
          ...
127627    166.0
127628    161.0
127629    159.0
127630    156.0
127631    147.0
Name: handicap_weight, Length: 127632, dtype: float64
0          92.0
1           NaN
2           NaN
3           NaN
4           NaN
          ...
127627      NaN
127628    131.0
127629    132.0
127630    143.0
127631    104.0
Name: run_2_final_rating_int, Length: 127632, dtype: float64

In [29]:
df_jump['race_type'] = df_jump['race_type'].iloc[:].astype("string")

In [30]:
df_jump['race_type'].dtypes

string[python]

In [31]:
df_jump

,meeting_id,meeting_name,date,event_number,distance,distance_furlongs,distance_raw_furlongs,race_class,race_class_normalised,total_prize_money,...,run_4_dsr,run_5_raw_post_race_rating_int,run_5_raw_post_race_rating_symbol,run_5_final_rating_int,run_5_race_type,run_5_race_class,run_5_race_class_normalised,run_5_track_type,run_5_win_lose,run_5_dsr
0,3671,MARKET RASEN,2020-07-20,1,3645,2m0.5f,16.6,4,Novice,5312,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3671,MARKET RASEN,2020-07-20,4,5251,2m8f,23.9,3,Handicap,9542,...,327.0,105.0,NaN,110.0,JUMP,3,Handicap,TURF,0.0,365.0
2,3671,MARKET RASEN,2020-07-20,4,5251,2m8f,23.9,3,Handicap,9542,...,801.0,111.0,NaN,124.0,JUMP,4,Novice,TURF,0.0,820.0
3,3671,MARKET RASEN,2020-07-20,4,5251,2m8f,23.9,3,Handicap,9542,...,484.0,NaN,NaN,NaN,STEEPLECHASE,3,Handicap,TURF,0.0,532.0
4,3671,MARKET RASEN,2020-07-20,4,5251,2m8f,23.9,3,Handicap,9542,...,383.0,NaN,NaN,NaN,STEEPLECHASE,3,Handicap,TURF,0.0,414.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127627,37980,MARKET RASEN,2023-09-30,4,4709,2m5.5f,21.4,3,Handicap,20974,...,372.0,131.0,NaN,133.0,STEEPLECHASE,3.0,Handicap,TURF,1.0,504.0
127628,37980,MARKET RASEN,2023-09-30,4,4709,2m5.5f,21.4,3,Handicap,20974,...,217.0,117.0,NaN,124.0,JUMP,4.0,Handicap,TURF,0.0,245.0
127629,37980,MARKET RASEN,2023-09-30,4,4709,2m5.5f,21.4,3,Handicap,20974,...,70.0,128.0,NaN,137.0,STEEPLECHASE,3.0,Handicap,TURF,1.0,98.0
127630,37980,MARKET RASEN,2023-09-30,4,4709,2m5.5f,21.4,3,Handicap,20974,...,212.0,131.0,?,143.0,JUMP,4.0,Handicap,TURF,1.0,220.0
127631,37980,MARKET RASEN,2023-09-30,7,4100,2m2.5f,18.6,5,Handicap,9534,...,141.0,70.0,NaN,91.0,JUMP,2.0,Handicap,TURF,0.0,190.0

In [32]:
df_jump['run_3_track_type'].unique()

array(['TURF', nan, 'AWT'], dtype=object)

In [33]:
#NEED TO FINISH CONVERTING OBJECTS THAT HAVE MORE THAN 1 TYPE
# AND NEED TO ENCODE SOMECOLUMNS
#Create a pipeline to automate this preprocessing pipeline

In [34]:
#

In [35]:
encoder = OneHotEncoder(sparse_output=False)

In [36]:
df_jump_encoded = df_jump.select_dtypes('object').iloc[:,1:]
df_jump_encoded

,distance_furlongs,race_class,race_class_normalised,track_condition,track_type,failed_to_finish_reason,gear,jockey_name,trainer_name,horse_name,...,run_4_raw_post_race_rating_symbol,run_4_race_type,run_4_race_class,run_4_race_class_normalised,run_4_track_type,run_5_raw_post_race_rating_symbol,run_5_race_type,run_5_race_class,run_5_race_class_normalised,run_5_track_type
0,2m0.5f,4,Novice,GOOD,TURF,NaN,NaN,Mr Luke Scott,Olly Murphy,Enchant Me,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2m8f,3,Handicap,GOOD,TURF,NaN,NaN,Ciaran Gethings,Stuart Edmunds,Hepijeu,...,NaN,STEEPLECHASE,3,Handicap,TURF,NaN,JUMP,3,Handicap,TURF
2,2m8f,3,Handicap,GOOD,TURF,NaN,NaN,David Bass,Kim Bailey,El Presente,...,NaN,JUMP,3,Handicap,TURF,NaN,JUMP,4,Novice,TURF
3,2m8f,3,Handicap,GOOD,TURF,NaN,NaN,Paddy Brennan,Henry Daly,Vice Et Vertu,...,NaN,STEEPLECHASE,3,Handicap,TURF,NaN,STEEPLECHASE,3,Handicap,TURF
4,2m8f,3,Handicap,GOOD,TURF,NaN,NaN,Adam Wedge,Emma Lavelle,Vendredi Trois,...,NaN,STEEPLECHASE,4,Handicap,TURF,NaN,STEEPLECHASE,3,Handicap,TURF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127627,2m5.5f,3,Handicap,GOOD,TURF,NaN,NaN,Sean Bowen,Martin Keighley,Found On,...,+,STEEPLECHASE,3.0,Novice,TURF,NaN,STEEPLECHASE,3.0,Handicap,TURF
127628,2m5.5f,3,Handicap,GOOD,TURF,NaN,NaN,Charlie Hammond,Jedd O'Keeffe,Vintage Fizz,...,NaN,JUMP,3.0,Handicap,TURF,NaN,JUMP,4.0,Handicap,TURF
127629,2m5.5f,3,Handicap,GOOD,TURF,PULLED_UP,TONGUE-TIE;CHEEKPIECES,Conor Rabbitt,Maurice Barnes,Saint Arvans,...,NaN,STEEPLECHASE,1.0,Handicap,TURF,NaN,STEEPLECHASE,3.0,Handicap,TURF
127630,2m5.5f,3,Handicap,GOOD,TURF,NaN,TONGUE-TIE,Adam Wedge,Evan Williams,Quoi De Neuf,...,NaN,STEEPLECHASE,3.0,Handicap,TURF,?,JUMP,4.0,Handicap,TURF
127631,2m2.5f,5,Handicap,GOOD,TURF,NaN,NaN,Danny McMenamin,Peter Niven,Misty Mani,...,NaN,JUMP,5.0,Handicap,TURF,NaN,JUMP,2.0,Handicap,TURF

In [37]:
encoder

OneHotEncoder(sparse_output=False)

In [38]:
pd.set_option('display.max_columns', 50)

In [39]:
temp_df_for_encoder = df_jump.select_dtypes('object').drop(columns = 'birth_date')

In [40]:
from sklearn.preprocessing import LabelEncoder

for col in temp_df_for_encoder.columns:
    temp_df_for_encoder[col]=LabelEncoder().fit_transform(temp_df_for_encoder[col])

temp_df_for_encoder

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']

In [41]:
#currrently have a label encoded data frame that still needs to be imputed and columns with multiple data types
#any data type object has been label encoded

In [42]:
#theres a directory called notebook

df_jump['run_2_race_type']

In [43]:
# encoders = {col: encoder.fit_transform(df_jump[col]) for col in temp_df_for_encoder}

# encoded_df= pd.DataFrame(
#     {col: encoders[col].fit_transform(df_jump[col]) for col in temp_df_for_encoder},
#     index=temp_df_for_encoder.index)

# encoded_df

In [44]:
# calculatean elo rating for the jockey to see the performance at each race

#Simply put, winning the races consistently will improve the
# rating and constantly losing hurts it. You gain more points
# when you win against stronger players and gain fewer when you win against weaker players than you.
# You lose more points against weaker players and fewer when you lose against stronger players than you.

In [45]:
df_jump.columns.get_loc('run_2_race_type')
#this is the location

53

In [46]:
df_jump_one_previous_race = df_jump.iloc[:,:41]

In [47]:
df_jump_one_previous_race['race_class_normalised'].unique()

array(['Novice', 'Handicap', 'Grade 2', 'Listed', 'Grade 3', nan,
       'Maiden', 'Selling', 'Grade 1', 'Conditions', 'Group 3',
       'Claiming'], dtype=object)

In [48]:
df_jump_one_previous_race = df_jump_one_previous_race[df_jump_one_previous_race['race_class_normalised']== 'Handicap']

In [50]:
df_jump_one_previous_race.columns

Index(['meeting_id', 'meeting_name', 'date', 'event_number', 'distance',
       'distance_furlongs', 'distance_raw_furlongs', 'race_class',
       'race_class_normalised', 'total_prize_money', 'track_condition',
       'race_type', 'track_type', 'barrier', 'number', 'finish_position',
       'win_or_lose', 'failed_to_finish_reason', 'margin', 'gear',
       'jockey_allowance', 'handicap_weight', 'jockey_id', 'jockey_name',
       'tainer_id', 'trainer_name', 'dslr', 'horse_id', 'horse_name', 'age',
       'birth_date', 'official rating', 'wfa', 'weight_adjustment',
       'bet365_odds', 'betfair_starting_price', 'pre_race_master_rating_int',
       'pre_race_master_rating_symbol', 'post_race_master_rating_int',
       'post_race_master_rating_symbol', 'starting_price'],
      dtype='object')

In [ ]:
if df_jump.select_dtypes == object :
    encoder = OneHotEncoder(sparse=False)
    encoded_df = encoder.fit_transform(df_jump)

In [ ]:
encoded_df

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
df_jump_one_previous_race.dtypes

In [ ]:
df_jump_one_previous_race.select_dtypes('float64')

In [ ]:
def preprocessing_pipeline() :
    numeric_features = []
    numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
    Pipe= Pipeline

In [ ]:
resultados_jump.drop(columns=['gear_nan'])

In [ ]:
resultados_jump['gear'] = resultados_jump['gear'].apply(lambda x: 0 if pd.isna(x) else 1)

In [ ]:
num_nan_per_columns = ((df_jump.isna().sum())/127632)*100
pd.set_option("display.max_rows", None, "display.max_columns", None) #show all the lines
num_nan_per_columns.sort_values()

In [ ]:
num_nan_per_columns = ((df_jump.isna().sum())/len(df_jump['starting_price']))*100
pd.set_option("display.max_rows", None, "display.max_columns", None) #show all the lines
num_nan_per_columns.sort_values()

In [ ]:
correlation_matrix = resultados_jump.corr()

In [ ]:
correlation_matrix

In [ ]:
plt.figure(figsize=(12, 10))  # Ajuste o tamanho da figura conforme necessário
sns.heatmap(correlation_matrix, center=0, cmap='coolwarm', fmt=".2f")
plt.show()

In [ ]:
porcentagem_nan = resultados_jump.isna().mean() * 100

# Filtrar as colunas com mais de 80% de NaN
colunas_com_nan_mais_de_80 = porcentagem_nan[porcentagem_nan > 80]

# Obter os nomes das colunas
nomes_colunas_com_nan_mais_de_80 = colunas_com_nan_mais_de_80.index.tolist()
nomes_colunas_com_nan_mais_de_80

In [ ]:
resultados_jump

In [ ]:
df_jump = df_jump.drop(columns=['failed_to_finish_reason',
 'pmu_odds',
 'post_race_master_rating_symbol',
 'run_1_raw_post_race_rating_symbol',
 'run_2_raw_post_race_rating_symbol',
 'run_3_raw_post_race_rating_symbol',
 'run_4_raw_post_race_rating_symbol',
 'run_5_raw_post_race_rating_symbol',
 'run_6_raw_post_race_rating_symbol',
 'run_7_raw_post_race_rating_symbol',
 'run_8_raw_post_race_rating_symbol'])

In [ ]:
df_jump

In [ ]:
'''THIS IS DAVIDS SPACE'''

In [ ]:
num_nan_per_columns_race = ((resultados_race.isna().sum())/len(resultados_race['starting_price']))*100
pd.set_option("display.max_rows", None, "display.max_columns", None) #show all the lines
num_nan_per_columns_race